### ISSUE TITLE
[BUG] /tools/go/go.tar.gz 这个文件似乎有问题

### ISSUE THREAD

**Issue by ranfish** [seccome/Ehoney#43]
**Bug 描述**

简要描述您碰到的问题

1. 系统环境:centos7
2. Ehoney版本:最新版本
3. 具体问题:/tools/go/go.tar.gz 这个文件似乎有问题

**Bug 重现步骤**

1.  脚本运行到解压这个文件会报错。
2. tar -xvf go.tar.gz 手动解压这个文件也会报错

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by afeiiiii** [comment]
谢谢您的反馈，该问题已经修复，请更新程序。
