### ISSUE TITLE
[BUG]修改密码、harbor仓库bug

### ISSUE THREAD

**Issue by devils** [seccome/Ehoney#44]
**Bug 描述**
1. 系统环境:Centos 7.6
2. Ehoney版本:v2.0.0重构版
3. 具体问题:1、修改密码导致无法登录；2、添加harbor仓库无效。

**Bug 1**
修改密码，数据库密码字段变成明文，导致无法登录。

**Bug 2**
添加完自己的harbor仓库后，镜像列表无法获取到新镜像，上个版本功能正常。

**Comment by zylhahah** [comment]
嗯嗯 疏忽了  你先使用123456密码的hash恢复吧 $2a$14$c2PTQQoSmPn/jTBwyenNZem44YNmpti2ZasKbU8RArS3byDkesPNq

**Comment by zylhahah** [comment]
Bug2 我们这边测试配置后是支持拉取到新镜像的（我们用的是2.0以上），确定一下是否有点击保存；如果还是不行提供一下harbor版本

**Comment by devils** [comment]
Harbor版本：2.3.0
