### ISSUE TITLE
[BUG] 管理端存在SQL注入漏洞

### ISSUE THREAD

**Issue by su18** [seccome/Ehoney#51]
**Bug 描述**

SQL注入漏洞

1. 系统环境:http://47.98.206.178:8080/decept-defense/
2. Ehoney版本:当前官方线上版本
3. 具体问题:诱捕管理-镜像列表-存在SQL注入漏洞

**Bug 重现步骤**

1.  查询 `www' or 1=1 -- -` 可返回所有结果
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/30317673/143379475-c19e5ffb-a9ce-467f-bc5a-4007dad24091.png">

2. 查询 `www' or 1=2 -- -` 返回结果为空

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/30317673/143379514-a9b5a61d-8008-4bb1-b05d-7b3fddaad61a.png">

3. 查询 `www' UNION all select 1,2,@@version,4,5,true -- -` 可以返回 mysql 版本
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/30317673/143379404-d91b3237-177d-47cd-b475-a0f7fc2b07b8.png">

**漏洞成因**

如下图，在 `models/Honeypot.go` 中的 `GetHoneypot` 方法，采取了字符串拼接的方式进行查询

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/30317673/143379631-f5245e46-581c-4286-83c6-82ecacca8c54.png">

**备注**

本Issues仅提供单一接口测试记录，其他接口也存在此问题，请自行查找。

**修复建议**

建议编写工具类对特殊请求进行过滤及防御，并采用预编译的技术防止SQL注入漏洞。

**Comment by l0ners** [comment]
> **Bug 描述**
> 
> SQL注入漏洞
> 
> 1. 系统环境:http://47.98.206.178:8080/decept-defense/
> 2. Ehoney版本:当前官方线上版本
> 3. 具体问题:诱捕管理-镜像列表-存在SQL注入漏洞
> 
> **Bug 重现步骤**
> 
> 1. 查询 `www' or 1=1 -- -` 可返回所有结果
> 
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/30317673/143379475-c19e5ffb-a9ce-467f-bc5a-4007dad24091.png">
> 
> 2. 查询 `www' or 1=2 -- -` 返回结果为空
> 
> <img alt="image" width="1256" src="https://user-images.githubusercontent.com/30317673/143379514-a9b5a61d-8008-4bb1-b05d-7b3fddaad61a.png">
> 
> 3. 查询 `www' UNION all select 1,2,@@version,4,5,true -- -` 可以返回 mysql 版本
> 
> <img alt="image" width="1267" src="https://user-images.githubusercontent.com/30317673/143379404-d91b3237-177d-47cd-b475-a0f7fc2b07b8.png">
> 
> **漏洞成因**
> 
> 如下图，在 `models/Honeypot.go` 中的 `GetHoneypot` 方法，采取了字符串拼接的方式进行查询
> 
> <img alt="image" width="1183" src="https://user-images.githubusercontent.com/30317673/143379631-f5245e46-581c-4286-83c6-82ecacca8c54.png">
> 
> **备注**
> 
> 本Issues仅提供单一接口测试记录，其他接口也存在此问题，请自行查找。
> 
> **修复建议**
> 
> 建议编写工具类对特殊请求进行过滤及防御，并采用预编译的技术防止SQL注入漏洞。

已临时使用过滤紧急修复

**Comment by zylhahah** [comment]
close
