### ISSUE TITLE
K8S创建镜像失败

### ISSUE THREAD

**Issue by DATA-GaMi** [seccome/Ehoney#53]
系统经过重新启动，想要再次部署蜜罐时报错
错误：K8S创建镜像失败
使用docker命令查看容器时发现
k8s_helm、k8s_metrics、k8s_local、k8s_falco都在创建一分钟后退出了

这个错误是什么原因导致的？

**Comment by T4di5** [comment]
> 系统经过重新启动，想要再次部署蜜罐时报错 错误：K8S创建镜像失败 使用docker命令查看容器时发现 k8s_helm、k8s_metrics、k8s_local、k8s_falco都在创建一分钟后退出了
> 
> 这个错误是什么原因导致的？

没人维护了，散了吧

**Comment by zylhahah** [comment]
> 系统经过重新启动，想要再次部署蜜罐时报错 错误：K8S创建镜像失败 使用docker命令查看容器时发现 k8s_helm、k8s_metrics、k8s_local、k8s_falco都在创建一分钟后退出了
> 
> 这个错误是什么原因导致的？

我们之前碰到类似的问题的原因是机器配置不够；推荐4核8G+50G硬盘的配置；如果问题还没解决+v: zyl9210018178
